apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lylics.fullname" . }}
  labels:
    {{- include "lylics.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "lylics.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "lylics.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.lyricsData }}
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            {{- $env := .Values.env }}
            {{- range $key := $env | keys | sortAlpha }}
            - name: {{ $key }}
              value: {{ index $env $key | quote }}
            {{- end }}
            {{- if .Values.lyricsData }}
            - name: LYLICS_DATA_PATH
              value: /data/lyrics.json
            {{- end }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- if .Values.lyricsData }}
          volumeMounts:
            - name: lyrics
              mountPath: /data
              readOnly: true
          {{- end }}
      {{- if .Values.lyricsData }}
      volumes:
        - name: lyrics
          configMap:
            name: {{ include "lylics.fullname" . }}-lyrics
      {{- end }}
